In [1]:
import torch


In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [10]:
torch.manual_seed(4)

features= torch.randn((1,5))

weights = torch.randn_like(features)

bias = torch.randn((1,1))

In [13]:
y = activation(torch.sum(features * weights) + bias)

In [14]:
y

tensor([[0.9916]])

In [15]:
y = activation((features * weights).sum() + bias)

In [16]:
y

tensor([[0.9916]])

In [17]:
torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:136

In [22]:
weights.shape

torch.Size([1, 5])

In [23]:
features.shape

torch.Size([1, 5])

In [25]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)
y

tensor([[0.9916]])

In [26]:
# A simple Neural Netowrk

In [27]:
torch.manual_seed(5)

# 3 features
features = torch.randn((1,3))

#size of each layer

n_input = features.shape[1]
n_hidden = 2
n_outpit = 1

# Weights for input - hidden layers
W1 = torch.randn(n_input, n_hidden)
#Weights for hidden - output

W2 = torch.randn(n_hidden, n_outpit)

#bias
B1= torch.randn((1, n_hidden))
B2 =  torch.randn((1, n_outpit))



In [30]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h,W2)+B2)
output

tensor([[0.1951]])

#### Numpy to torch 

In [32]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.54044514, 0.95427933, 0.0481386 ],
       [0.393218  , 0.25772052, 0.96683398],
       [0.86657708, 0.81363625, 0.3424469 ],
       [0.99741084, 0.5631593 , 0.78597736]])

In [33]:
b = torch.from_numpy(a)

In [34]:
b

tensor([[0.5404, 0.9543, 0.0481],
        [0.3932, 0.2577, 0.9668],
        [0.8666, 0.8136, 0.3424],
        [0.9974, 0.5632, 0.7860]], dtype=torch.float64)

In [35]:
b.numpy()

array([[0.54044514, 0.95427933, 0.0481386 ],
       [0.393218  , 0.25772052, 0.96683398],
       [0.86657708, 0.81363625, 0.3424469 ],
       [0.99741084, 0.5631593 , 0.78597736]])

In [36]:
b.mul_(2)

tensor([[1.0809, 1.9086, 0.0963],
        [0.7864, 0.5154, 1.9337],
        [1.7332, 1.6273, 0.6849],
        [1.9948, 1.1263, 1.5720]], dtype=torch.float64)

In [37]:
a

array([[1.08089029, 1.90855865, 0.09627719],
       [0.78643599, 0.51544104, 1.93366797],
       [1.73315416, 1.6272725 , 0.68489381],
       [1.99482169, 1.12631859, 1.57195471]])